const hiddenFooter = { display: "none" } as const

export const clerkUserProfileAppearance = {
  variables: {
    colorBackground: "#050a14",
    colorForeground: "#e6f3ff",
    colorMuted: "#12253d",
    colorMutedForeground: "#87abcf",
    colorPrimary: "#10c7ff",
    colorPrimaryForeground: "#03101f",
    colorDanger: "#ff4d70",
    colorSuccess: "#0ac97d",
    colorWarning: "#f5a524",
    colorNeutral: "#6e93b8",
    colorInput: "#274669",
    colorInputForeground: "#e6f3ff",
    colorBorder: "#223e63",
    colorRing: "#11bfff",
    colorText: "#e6f3ff",
    colorTextSecondary: "#87abcf",
    colorTextOnPrimaryBackground: "#03101f",
    borderRadius: "0.75rem",
    fontFamily: "var(--font-marketing-sans), system-ui, sans-serif",
    fontFamilyButtons: "var(--font-marketing-sans), system-ui, sans-serif",
  },
  elements: {
    rootBox: "w-full max-w-3xl mx-auto",
    cardBox:
      "w-full max-h-[min(28rem,calc(100dvh-10rem))] rounded-3xl border border-white/10 bg-[#07172a]/55 shadow-[0_24px_80px_rgb(3_8_18/0.55),0_0_0_1px_rgb(17_201_255/0.08)_inset] backdrop-blur-xl",
    card: "h-full max-h-[min(28rem,calc(100dvh-10rem))] bg-transparent shadow-none",
    navbar: "max-h-[min(28rem,calc(100dvh-10rem))] border-white/10 bg-[#050a14]/80",
    navbarFooter: hiddenFooter,
    navbarButton:
      "text-[#87abcf] hover:bg-white/[0.06] hover:text-[#e6f3ff] data-[active=true]:bg-white/[0.08] data-[active=true]:text-accent-neon",
    navbarButtonIcon: "text-current",
    pageScrollBox: "max-h-[min(24rem,calc(100dvh-12rem))] overflow-y-auto bg-transparent",
    page: "bg-transparent text-[#e6f3ff]",
    scrollBox: "max-h-[min(28rem,calc(100dvh-10rem))]",
    headerTitle: "text-[#e6f3ff] [font-family:var(--font-marketing-heading)]",
    headerSubtitle: "text-[#87abcf]",
    profileSectionTitle: "text-[#e6f3ff]",
    profileSectionContent: "text-[#87abcf]",
    profileSectionPrimaryButton: "text-accent-neon hover:text-[#e6f3ff]",
    formFieldLabel: "text-[#87abcf]",
    formFieldInput:
      "rounded-xl border border-white/12 bg-white/[0.04] text-[#e6f3ff] placeholder:text-[#6e93b8] focus:border-accent-neon/50 focus:ring-accent-neon/20",
    formButtonPrimary:
      "rounded-xl border border-[#b8ebff]/70 bg-[#ecf8ff] text-sm font-semibold text-[#03101f] shadow-[0_10px_24px_rgb(17_191_255/0.18)] hover:bg-white",
    formButtonReset: "text-[#87abcf] hover:text-[#e6f3ff]",
    badge: "border border-white/12 bg-white/[0.06] text-[#87abcf]",
    menuButton: "text-[#87abcf] hover:text-[#e6f3ff]",
    menuList: "border border-white/10 bg-[#0a1627]",
    menuItem: "text-[#e6f3ff] hover:bg-white/[0.06]",
    accordionTriggerButton: "text-[#e6f3ff]",
    footer: hiddenFooter,
    footerAction: hiddenFooter,
    footerPages: hiddenFooter,
    footerActionLink: hiddenFooter,
    footerActionText: hiddenFooter,
    internal: hiddenFooter,
    developmentModeIndicator: hiddenFooter,
    clerkBranding: hiddenFooter,
  },
  options: {
    unsafe_disableDevelopmentModeWarnings: true,
  },
}
