/**
 * Fetches Hyperliquid meta (default + xyz dex) and Binance USDT-M perpetuals,
 * then writes lib/markets.generated.ts with intersected crypto + all xyz assets.
 *
 * Run: npm run markets:refresh
 */
import { writeFileSync } from "node:fs"
import { dirname, join } from "node:path"
import { fileURLToPath } from "node:url"
import type { AssetCategory, Market, PriceSource } from "../lib/markets-types"

const __dirname = dirname(fileURLToPath(import.meta.url))
const OUT = join(__dirname, "..", "lib", "markets.generated.ts")

type HlUniverseEntry = {
  name: string
  maxLeverage: number
  szDecimals: number
  isDelisted?: boolean
}

type HlMeta = {
  universe: HlUniverseEntry[]
}

type BinanceSymbolInfo = {
  symbol: string
  contractType: string
  quoteAsset: string
  status: string
}

const hlNameToBinancePerp = (hlName: string): string | null => {
  if (hlName.startsWith("xyz:")) {
    return null
  }
  if (hlName.startsWith("k")) {
    return `1000${hlName.slice(1)}USDT`
  }
  return `${hlName}USDT`
}

const COMMODITY_BASES = new Set([
  "GOLD",
  "SILVER",
  "COPPER",
  "PLATINUM",
  "PALLADIUM",
  "BRENTOIL",
  "CL",
  "NATGAS",
  "ALUMINIUM",
])

const INDEX_BASES = new Set([
  "XYZ100",
  "SP500",
  "JP225",
  "KR200",
  "EWJ",
  "EWY",
  "EUR",
  "JPY",
])

/** TradingView overrides for non-obvious symbols */
const TV_OVERRIDES: Record<string, string> = {
  "xyz:GOOGL": "NASDAQ:GOOGL",
  "xyz:BRK.B": "NYSE:BRK.B",
  "xyz:SP500": "SP:SPX",
  "xyz:JP225": "TVC:NI225",
  "xyz:KR200": "KRX:KOSPI200",
  "xyz:XYZ100": "NASDAQ:NDX",
  "xyz:EUR": "FX:EURUSD",
  "xyz:JPY": "FX:USDJPY",
  "xyz:BRENTOIL": "TVC:UKOIL",
  "xyz:CL": "TVC:USOIL",
  "xyz:NATGAS": "TVC:NGAS",
  "xyz:GOLD": "TVC:GOLD",
  "xyz:SILVER": "TVC:SILVER",
  "xyz:COPPER": "TVC:COPPER",
  "xyz:PLATINUM": "TVC:PLATINUM",
  "xyz:PALLADIUM": "TVC:PALLADIUM",
}

const categorizeXyz = (base: string): AssetCategory => {
  if (COMMODITY_BASES.has(base)) {
    return "commodity"
  }
  if (INDEX_BASES.has(base)) {
    return "index"
  }
  return "equity"
}

const tvSymbolForXyz = (hlName: string, base: string): string => {
  const override = TV_OVERRIDES[hlName]
  if (override) {
    return override
  }
  const cat = categorizeXyz(base)
  if (cat === "equity") {
    return `NASDAQ:${base}`
  }
  if (cat === "commodity") {
    return `TVC:${base}`
  }
  return `TVC:${base}`
}

const fetchJson = async <T>(url: string, init?: RequestInit): Promise<T> => {
  const res = await fetch(url, init)
  if (!res.ok) {
    throw new Error(`HTTP ${res.status} ${url}`)
  }
  return (await res.json()) as T
}

const main = async () => {
  const [exchangeInfo, metaDefault, metaXyz] = await Promise.all([
    fetchJson<{ symbols: BinanceSymbolInfo[] }>("https://fapi.binance.com/fapi/v1/exchangeInfo"),
    fetchJson<HlMeta>("https://api.hyperliquid.xyz/info", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ type: "meta" }),
    }),
    fetchJson<HlMeta>("https://api.hyperliquid.xyz/info", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ type: "meta", dex: "xyz" }),
    }),
  ])

  const binancePerps = new Set(
    exchangeInfo.symbols
      .filter(
        (s) =>
          s.contractType === "PERPETUAL" &&
          s.quoteAsset === "USDT" &&
          s.status === "TRADING",
      )
      .map((s) => s.symbol),
  )

  const markets: Market[] = []

  for (const entry of metaDefault.universe) {
    if (entry.isDelisted) {
      continue
    }
    const binSym = hlNameToBinancePerp(entry.name)
    if (!binSym || !binancePerps.has(binSym)) {
      continue
    }
    markets.push({
      symbol: binSym,
      hlName: entry.name,
      displayName: `${entry.name}-USD`,
      base: entry.name,
      category: "crypto",
      maxLeverage: entry.maxLeverage,
      szDecimals: entry.szDecimals,
      priceSource: "binance-futures" as PriceSource,
      binanceSymbol: binSym,
      hlPriceKey: entry.name,
      tvSymbol: `BINANCE:${binSym}.P`,
    })
  }

  for (const entry of metaXyz.universe) {
    if (entry.isDelisted) {
      continue
    }
    if (!entry.name.startsWith("xyz:")) {
      continue
    }
    const base = entry.name.slice(4)
    const category = categorizeXyz(base)
    markets.push({
      symbol: entry.name,
      hlName: entry.name,
      displayName: base,
      base,
      category,
      maxLeverage: entry.maxLeverage,
      szDecimals: entry.szDecimals,
      priceSource: "hyperliquid",
      hlPriceKey: entry.name,
      tvSymbol: tvSymbolForXyz(entry.name, base),
    })
  }

  markets.sort((a, b) => a.symbol.localeCompare(b.symbol))

  const header = `// AUTO-GENERATED by scripts/fetch-hl-markets.ts — run npm run markets:refresh
import type { Market } from "./markets-types"

`

  const body = `export const MARKETS_SNAPSHOT: readonly Market[] = ${JSON.stringify(markets, null, 2)} as const
`

  writeFileSync(OUT, header + body, "utf8")
  console.log(`Wrote ${markets.length} markets to lib/markets.generated.ts`)
}

main().catch((err) => {
  console.error(err)
  process.exit(1)
})
